-- =========================================================
-- MANUAL CLEANUP SCRIPT - Run this FIRST if you have issues
-- =========================================================

-- Drop the specific problematic trigger
DROP TRIGGER SUMMERCLUB.ACTIVITY_ID_TRIGGER;

-- Drop all foreign key constraints
ALTER TABLE SUMMERCLUB.EMPLOYEES DROP CONSTRAINT FK_EMPLOYEE_ACTIVITY;
ALTER TABLE SUMMERCLUB.PARTICIPATE DROP CONSTRAINT FK_PARTICIPATE_MEMBER;
ALTER TABLE SUMMERCLUB.PARTICIPATE DROP CONSTRAINT FK_PARTICIPATE_ACTIVITY;
ALTER TABLE SUMMERCLUB.MANAGE DROP CONSTRAINT FK_MANAGE_EMPLOYEE;
ALTER TABLE SUMMERCLUB.MANAGE DROP CONSTRAINT FK_MANAGE_EQUIPMENT;
ALTER TABLE SUMMERCLUB.TRANSACTIONS DROP CONSTRAINT FK_TRANSACTIONS_EMPLOYEE;

-- Drop all tables
DROP TABLE SUMMERCLUB.PARTICIPATE CASCADE CONSTRAINTS;
DROP TABLE SUMMERCLUB.MANAGE CASCADE CONSTRAINTS;
DROP TABLE SUMMERCLUB.TRANSACTIONS CASCADE CONSTRAINTS;
DROP TABLE SUMMERCLUB.EMPLOYEES CASCADE CONSTRAINTS;
DROP TABLE SUMMERCLUB.ACTIVITIES CASCADE CONSTRAINTS;
DROP TABLE SUMMERCLUB.EQUIPEMENTS CASCADE CONSTRAINTS;
DROP TABLE SUMMERCLUB.MEMBERS CASCADE CONSTRAINTS;

-- Drop sequences
DROP SEQUENCE SUMMERCLUB.ACTIVITY_ID_SEQ;
DROP SEQUENCE SUMMERCLUB.EQUIPMENT_ID_SEQ;
DROP SEQUENCE SUMMERCLUB.TRANSACTION_ID_SEQ;

-- Commit the cleanup
COMMIT;

SELECT 'Cleanup completed successfully!' AS message FROM dual;