--------------------------------------------------------
--  File created - Thursday-November-20-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ACTIVITY_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SUMMERCLUB"."ACTIVITY_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EQUIPMENT_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SUMMERCLUB"."EQUIPMENT_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RESERVATIONS
--------------------------------------------------------

   CREATE SEQUENCE  "SUMMERCLUB"."SEQ_RESERVATIONS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRANSACTION_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SUMMERCLUB"."TRANSACTION_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ACTIVITIES
--------------------------------------------------------

  CREATE TABLE "SUMMERCLUB"."ACTIVITIES" 
   (	"ID_A" NUMBER, 
	"ACTIVITY_TYPE" VARCHAR2(50 BYTE), 
	"EVENT_DATE" DATE, 
	"EVENT_TIME" TIMESTAMP (6), 
	"RESPONSIBLE" VARCHAR2(100 BYTE), 
	"AGE_REQUIREMENT" NUMBER(3,0), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'Scheduled', 
	"DESCRIPTION" CLOB, 
	"CAPACITY" NUMBER(5,0), 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"DURATION_MINUTES" NUMBER DEFAULT 60
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("DESCRIPTION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "SUMMERCLUB"."EMPLOYEES" 
   (	"CIN" VARCHAR2(50 BYTE), 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"POSITION" VARCHAR2(50 BYTE), 
	"DEPARTMENT" VARCHAR2(50 BYTE), 
	"HIRE_DATE" DATE, 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'Active', 
	"AGE" NUMBER(3,0), 
	"GENDER" VARCHAR2(10 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"SALARY" NUMBER(10,2), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"PHOTO" BLOB, 
	"ID_A" NUMBER, 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("PHOTO") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENTS
--------------------------------------------------------

  CREATE TABLE "SUMMERCLUB"."EQUIPEMENTS" 
   (	"ID_EQ" NUMBER, 
	"EQUIP_CODE" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"CATEGORY" VARCHAR2(50 BYTE), 
	"TOTAL_QUANTITY" NUMBER(5,0), 
	"AVAILABLE" NUMBER DEFAULT 0, 
	"IN_USE" NUMBER(5,0), 
	"UNDER_MAINTENANCE" NUMBER(5,0), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'Available', 
	"BRAND" VARCHAR2(50 BYTE), 
	"MODEL" VARCHAR2(50 BYTE), 
	"PURCHASE_DATE" DATE, 
	"PURCHASE_PRICE" NUMBER(10,2), 
	"LOCATION" VARCHAR2(100 BYTE), 
	"NOTES" CLOB, 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"RESERVED" NUMBER DEFAULT 0, 
	"QUANTITY_AVAILABLE" NUMBER(*,0) DEFAULT 0, 
	"QUANTITY_RESERVED" NUMBER(*,0) DEFAULT 0, 
	"QUANTITY_MAINTENANCE" NUMBER(*,0) DEFAULT 0, 
	"QUANTITY_OUT_OF_ORDER" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("NOTES") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table EQUIPMENT_RESERVATIONS
--------------------------------------------------------

  CREATE TABLE "SUMMERCLUB"."EQUIPMENT_RESERVATIONS" 
   (	"ID_RESERVATION" NUMBER(*,0), 
	"ID_ACTIVITY" NUMBER(*,0), 
	"ID_EQUIPMENT" NUMBER(*,0), 
	"QUANTITY_RESERVED" NUMBER(*,0), 
	"RESERVATION_DATE" DATE, 
	"RETURN_DATE" DATE, 
	"STATUS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MANAGE
--------------------------------------------------------

  CREATE TABLE "SUMMERCLUB"."MANAGE" 
   (	"CIN" VARCHAR2(50 BYTE), 
	"ID_EQ" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBERS
--------------------------------------------------------

  CREATE TABLE "SUMMERCLUB"."MEMBERS" 
   (	"CIN" VARCHAR2(50 BYTE), 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"GENDER" VARCHAR2(10 BYTE), 
	"AGE" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"SUBSCRIPTION_PLAN" VARCHAR2(50 BYTE), 
	"JOIN_DATE" DATE, 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"UPDATED_DATE" DATE DEFAULT SYSDATE, 
	"PHOTO" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("PHOTO") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PARTICIPATE
--------------------------------------------------------

  CREATE TABLE "SUMMERCLUB"."PARTICIPATE" 
   (	"CIN" VARCHAR2(50 BYTE), 
	"ID_A" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRANSACTIONS
--------------------------------------------------------

  CREATE TABLE "SUMMERCLUB"."TRANSACTIONS" 
   (	"ID_TR" NUMBER, 
	"TRANSACTION_ID" VARCHAR2(100 BYTE), 
	"PAYMENT_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"PAYMENT_TYPE" VARCHAR2(50 BYTE), 
	"AMOUNT" NUMBER(10,2), 
	"PAYMENT_METHOD" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'Pending', 
	"MEMBER_ID" VARCHAR2(50 BYTE), 
	"CIN" VARCHAR2(50 BYTE), 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SUMMERCLUB.ACTIVITIES
SET DEFINE OFF;
Insert into SUMMERCLUB.ACTIVITIES (ID_A,ACTIVITY_TYPE,EVENT_DATE,EVENT_TIME,RESPONSIBLE,AGE_REQUIREMENT,STATUS,CAPACITY,CREATED_DATE,UPDATED_DATE,DURATION_MINUTES) values (1,'Group Class',to_date('05-NOV-25','DD-MON-RR'),to_timestamp('05-NOV-25 04.03.33.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'KhalilAAAAAAAAAAAAAAAAAAA',5,'Scheduled',30,to_timestamp('06-NOV-25 11.31.54.956000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('06-NOV-25 11.31.54.956000000 PM','DD-MON-RR HH.MI.SSXFF AM'),60);
Insert into SUMMERCLUB.ACTIVITIES (ID_A,ACTIVITY_TYPE,EVENT_DATE,EVENT_TIME,RESPONSIBLE,AGE_REQUIREMENT,STATUS,CAPACITY,CREATED_DATE,UPDATED_DATE,DURATION_MINUTES) values (2,'Group Class',to_date('01-FEB-26','DD-MON-RR'),to_timestamp('01-FEB-26 02.33.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Yasmine Hidri',18,'In Progress',30,to_timestamp('06-NOV-25 11.31.54.962000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('06-NOV-25 11.31.54.962000000 PM','DD-MON-RR HH.MI.SSXFF AM'),60);
Insert into SUMMERCLUB.ACTIVITIES (ID_A,ACTIVITY_TYPE,EVENT_DATE,EVENT_TIME,RESPONSIBLE,AGE_REQUIREMENT,STATUS,CAPACITY,CREATED_DATE,UPDATED_DATE,DURATION_MINUTES) values (3,'Group Class',to_date('01-APR-06','DD-MON-RR'),to_timestamp('01-APR-06 04.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'aachek',18,'Scheduled',30,to_timestamp('06-NOV-25 11.32.19.684000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('06-NOV-25 11.32.19.684000000 PM','DD-MON-RR HH.MI.SSXFF AM'),60);
Insert into SUMMERCLUB.ACTIVITIES (ID_A,ACTIVITY_TYPE,EVENT_DATE,EVENT_TIME,RESPONSIBLE,AGE_REQUIREMENT,STATUS,CAPACITY,CREATED_DATE,UPDATED_DATE,DURATION_MINUTES) values (21,'Group Class',to_date('01-JAN-00','DD-MON-RR'),to_timestamp('01-JAN-00 04.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'khail cheruf',18,'Cancelled',30,to_timestamp('14-NOV-25 09.30.54.740000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('14-NOV-25 09.30.54.740000000 AM','DD-MON-RR HH.MI.SSXFF AM'),60);
REM INSERTING into SUMMERCLUB.EMPLOYEES
SET DEFINE OFF;
Insert into SUMMERCLUB.EMPLOYEES (CIN,FIRST_NAME,LAST_NAME,POSITION,DEPARTMENT,HIRE_DATE,STATUS,AGE,GENDER,EMAIL,PHONE,SALARY,PASSWORD,ID_A,CREATED_DATE,UPDATED_DATE) values ('11111111','testaa','test','Manager','Activity Management',to_date('07-NOV-25','DD-MON-RR'),'Active',25,'Male','test@esprit.tn','55657876',111,'khalil',null,to_timestamp('07-NOV-25 10.31.46.235000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('07-NOV-25 12.00.36.004000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SUMMERCLUB.EMPLOYEES (CIN,FIRST_NAME,LAST_NAME,POSITION,DEPARTMENT,HIRE_DATE,STATUS,AGE,GENDER,EMAIL,PHONE,SALARY,PASSWORD,ID_A,CREATED_DATE,UPDATED_DATE) values ('11111112','khail','cheruf','Manager','Activity Management',to_date('07-NOV-25','DD-MON-RR'),'Active',25,'Male','k@a.com','11111111',55555555,'11111111',null,to_timestamp('07-NOV-25 12.00.10.318000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('14-NOV-25 10.11.09.337000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SUMMERCLUB.EMPLOYEES (CIN,FIRST_NAME,LAST_NAME,POSITION,DEPARTMENT,HIRE_DATE,STATUS,AGE,GENDER,EMAIL,PHONE,SALARY,PASSWORD,ID_A,CREATED_DATE,UPDATED_DATE) values ('11111119','khalil','omar','Manager','Activity Management',to_date('07-NOV-25','DD-MON-RR'),'Active',25,'Male','khailo@mar.com','44444444',150,'khalil111',null,to_timestamp('07-NOV-25 12.15.03.804000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('07-NOV-25 12.15.03.804000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SUMMERCLUB.EMPLOYEES (CIN,FIRST_NAME,LAST_NAME,POSITION,DEPARTMENT,HIRE_DATE,STATUS,AGE,GENDER,EMAIL,PHONE,SALARY,PASSWORD,ID_A,CREATED_DATE,UPDATED_DATE) values ('11111118','cherif','khalil','Manager','Activity Management',to_date('14-NOV-25','DD-MON-RR'),'Active',25,'Male','khalil@gmail.com','77777777',44,'kihazd1',null,to_timestamp('14-NOV-25 10.10.50.276000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('14-NOV-25 10.10.50.276000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into SUMMERCLUB.EQUIPEMENTS
SET DEFINE OFF;
Insert into SUMMERCLUB.EQUIPEMENTS (ID_EQ,EQUIP_CODE,NAME,CATEGORY,TOTAL_QUANTITY,AVAILABLE,IN_USE,UNDER_MAINTENANCE,STATUS,BRAND,MODEL,PURCHASE_DATE,PURCHASE_PRICE,LOCATION,CREATED_DATE,UPDATED_DATE,RESERVED,QUANTITY_AVAILABLE,QUANTITY_RESERVED,QUANTITY_MAINTENANCE,QUANTITY_OUT_OF_ORDER) values (41,'EQ001','Swimming ABDIBIAZ','Cardio',10,8,null,null,'Available','AquaTech',null,null,null,'Pool Area',to_timestamp('13-NOV-25 05.47.37.230000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('13-NOV-25 05.47.37.230000000 PM','DD-MON-RR HH.MI.SSXFF AM'),0,8,null,null,0);
Insert into SUMMERCLUB.EQUIPEMENTS (ID_EQ,EQUIP_CODE,NAME,CATEGORY,TOTAL_QUANTITY,AVAILABLE,IN_USE,UNDER_MAINTENANCE,STATUS,BRAND,MODEL,PURCHASE_DATE,PURCHASE_PRICE,LOCATION,CREATED_DATE,UPDATED_DATE,RESERVED,QUANTITY_AVAILABLE,QUANTITY_RESERVED,QUANTITY_MAINTENANCE,QUANTITY_OUT_OF_ORDER) values (62,'EQ-87423','TYGDJ','Strength Training',1,1,0,0,'Available','dfg','fhjju',to_date('01-JAN-00','DD-MON-RR'),23467,'N/A',to_timestamp('14-NOV-25 09.29.53.595000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('14-NOV-25 09.29.53.595000000 AM','DD-MON-RR HH.MI.SSXFF AM'),0,1,0,0,0);
REM INSERTING into SUMMERCLUB.EQUIPMENT_RESERVATIONS
SET DEFINE OFF;
REM INSERTING into SUMMERCLUB.MANAGE
SET DEFINE OFF;
REM INSERTING into SUMMERCLUB.MEMBERS
SET DEFINE OFF;
Insert into SUMMERCLUB.MEMBERS (CIN,FIRST_NAME,LAST_NAME,GENDER,AGE,EMAIL,PHONE,SUBSCRIPTION_PLAN,JOIN_DATE,CREATED_DATE,UPDATED_DATE) values ('12345678','John','Doe','Male',18,'john.doe@example.com','55567876','Monthly',to_date('05-NOV-25','DD-MON-RR'),to_date('06-NOV-25','DD-MON-RR'),to_date('06-NOV-25','DD-MON-RR'));
Insert into SUMMERCLUB.MEMBERS (CIN,FIRST_NAME,LAST_NAME,GENDER,AGE,EMAIL,PHONE,SUBSCRIPTION_PLAN,JOIN_DATE,CREATED_DATE,UPDATED_DATE) values ('11112222','Ahmad','Ali','Male',18,'ahmad@example.com','55555555','Monthly',to_date('05-NOV-25','DD-MON-RR'),to_date('06-NOV-25','DD-MON-RR'),to_date('06-NOV-25','DD-MON-RR'));
Insert into SUMMERCLUB.MEMBERS (CIN,FIRST_NAME,LAST_NAME,GENDER,AGE,EMAIL,PHONE,SUBSCRIPTION_PLAN,JOIN_DATE,CREATED_DATE,UPDATED_DATE) values ('11111115','Sara','Ben Salah','Female',18,'sara@example.com','11111111','Monthly',to_date('05-NOV-25','DD-MON-RR'),to_date('06-NOV-25','DD-MON-RR'),to_date('06-NOV-25','DD-MON-RR'));
Insert into SUMMERCLUB.MEMBERS (CIN,FIRST_NAME,LAST_NAME,GENDER,AGE,EMAIL,PHONE,SUBSCRIPTION_PLAN,JOIN_DATE,CREATED_DATE,UPDATED_DATE) values ('11111111','aaa','aaaa','Male',25,'khail05cherif@gmail.com','11111111','Monthly',to_date('01-JAN-00','DD-MON-RR'),to_date('07-NOV-25','DD-MON-RR'),to_date('07-NOV-25','DD-MON-RR'));
Insert into SUMMERCLUB.MEMBERS (CIN,FIRST_NAME,LAST_NAME,GENDER,AGE,EMAIL,PHONE,SUBSCRIPTION_PLAN,JOIN_DATE,CREATED_DATE,UPDATED_DATE) values ('01928365','yassine','hosni','Male',22,'zaudbidiazbida@gmail.com','98646353','Monthly',to_date('01-JAN-25','DD-MON-RR'),to_date('14-NOV-25','DD-MON-RR'),to_date('14-NOV-25','DD-MON-RR'));
Insert into SUMMERCLUB.MEMBERS (CIN,FIRST_NAME,LAST_NAME,GENDER,AGE,EMAIL,PHONE,SUBSCRIPTION_PLAN,JOIN_DATE,CREATED_DATE,UPDATED_DATE) values ('12345670','yass','ghsui','Male',25,'gsuhva@gmail.com','56784367','Monthly',to_date('01-JAN-00','DD-MON-RR'),to_date('14-NOV-25','DD-MON-RR'),to_date('14-NOV-25','DD-MON-RR'));
REM INSERTING into SUMMERCLUB.PARTICIPATE
SET DEFINE OFF;
Insert into SUMMERCLUB.PARTICIPATE (CIN,ID_A) values ('11112222',2);
Insert into SUMMERCLUB.PARTICIPATE (CIN,ID_A) values ('12345678',1);
REM INSERTING into SUMMERCLUB.TRANSACTIONS
SET DEFINE OFF;
Insert into SUMMERCLUB.TRANSACTIONS (ID_TR,TRANSACTION_ID,PAYMENT_DATE,DESCRIPTION,PAYMENT_TYPE,AMOUNT,PAYMENT_METHOD,STATUS,MEMBER_ID,CIN,CREATED_DATE,UPDATED_DATE) values (1,'TXN001',to_date('14-NOV-25','DD-MON-RR'),'Monthly membership fee','Income',50,'Credit Card','Completed','11111111',null,to_timestamp('06-NOV-25 11.31.55.036000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('06-NOV-25 11.31.55.036000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SUMMERCLUB.TRANSACTIONS (ID_TR,TRANSACTION_ID,PAYMENT_DATE,DESCRIPTION,PAYMENT_TYPE,AMOUNT,PAYMENT_METHOD,STATUS,MEMBER_ID,CIN,CREATED_DATE,UPDATED_DATE) values (2,'TXN002',to_date('14-NOV-25','DD-MON-RR'),'Equipment rental','Income',25,'Cash','Completed','12345678',null,to_timestamp('06-NOV-25 11.31.55.042000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('06-NOV-25 11.31.55.042000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SUMMERCLUB.TRANSACTIONS (ID_TR,TRANSACTION_ID,PAYMENT_DATE,DESCRIPTION,PAYMENT_TYPE,AMOUNT,PAYMENT_METHOD,STATUS,MEMBER_ID,CIN,CREATED_DATE,UPDATED_DATE) values (22,'TXN004',to_date('08-OCT-25','DD-MON-RR'),'fghj','Income',23,'Cash','Completed','11111111',null,to_timestamp('14-NOV-25 09.32.27.683000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('14-NOV-25 09.32.27.683000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SUMMERCLUB.TRANSACTIONS (ID_TR,TRANSACTION_ID,PAYMENT_DATE,DESCRIPTION,PAYMENT_TYPE,AMOUNT,PAYMENT_METHOD,STATUS,MEMBER_ID,CIN,CREATED_DATE,UPDATED_DATE) values (23,'TXN005',to_date('14-NOV-25','DD-MON-RR'),'GOODMORNING','Income',100.1,'Cash','Completed','11111111',null,to_timestamp('14-NOV-25 10.20.08.625000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('14-NOV-25 10.20.08.625000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
--------------------------------------------------------
--  DDL for Index PK_ACTIVITY
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUMMERCLUB"."PK_ACTIVITY" ON "SUMMERCLUB"."ACTIVITIES" ("ID_A") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MANAGE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUMMERCLUB"."PK_MANAGE" ON "SUMMERCLUB"."MANAGE" ("CIN", "ID_EQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PARTICIPATE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUMMERCLUB"."PK_PARTICIPATE" ON "SUMMERCLUB"."PARTICIPATE" ("CIN", "ID_A") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUMMERCLUB"."PK_MEMBERS" ON "SUMMERCLUB"."MEMBERS" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_TRANSACTION_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUMMERCLUB"."UK_TRANSACTION_ID" ON "SUMMERCLUB"."TRANSACTIONS" ("TRANSACTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TRANSACTIONS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUMMERCLUB"."PK_TRANSACTIONS" ON "SUMMERCLUB"."TRANSACTIONS" ("ID_TR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EMPLOYEES
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUMMERCLUB"."PK_EMPLOYEES" ON "SUMMERCLUB"."EMPLOYEES" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger ACTIVITY_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SUMMERCLUB"."ACTIVITY_ID_TRIGGER" 
    BEFORE INSERT ON SUMMERCLUB.ACTIVITIES
    FOR EACH ROW
BEGIN
    IF :NEW.ID_A IS NULL THEN
        :NEW.ID_A := SUMMERCLUB.ACTIVITY_ID_SEQ.NEXTVAL;
    END IF;
END;


/
ALTER TRIGGER "SUMMERCLUB"."ACTIVITY_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_EQUIPMENT_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SUMMERCLUB"."TRG_EQUIPMENT_ID" 
BEFORE INSERT ON EQUIPEMENTS FOR EACH ROW
BEGIN
    IF :NEW.ID_EQ IS NULL THEN
        :NEW.ID_EQ := EQUIPMENT_ID_SEQ.NEXTVAL;
    END IF;
END;
/
ALTER TRIGGER "SUMMERCLUB"."TRG_EQUIPMENT_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TRANSACTION_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SUMMERCLUB"."TRG_TRANSACTION_ID" 
    BEFORE INSERT ON SUMMERCLUB.TRANSACTIONS
    FOR EACH ROW
BEGIN
    IF :NEW.ID_TR IS NULL THEN
        :NEW.ID_TR := SUMMERCLUB.TRANSACTION_ID_SEQ.NEXTVAL;
    END IF;
END;


/
ALTER TRIGGER "SUMMERCLUB"."TRG_TRANSACTION_ID" ENABLE;
--------------------------------------------------------
--  DDL for Procedure RECOMPUTE_EQUIPMENT_RESERVED
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "SUMMERCLUB"."RECOMPUTE_EQUIPMENT_RESERVED" (p_id_eq IN NUMBER) AS
    v_reserved NUMBER := 0;
BEGIN
    /* Count confirmed reservations that are current OR future.
       You can adjust the condition if you want other semantics. */
    SELECT NVL(SUM(QUANTITY),0)
      INTO v_reserved
      FROM SUMMERCLUB.RESERVATIONS r
     WHERE r.ID_EQ = p_id_eq
       AND r.STATUS = 'CONFIRMED'
       AND r.DATE_FIN >= TRUNC(SYSDATE);  -- only current/future reservations

    UPDATE SUMMERCLUB.EQUIPEMENTS
       SET RESERVED = v_reserved
     WHERE ID_EQ = p_id_eq;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        NULL; -- nothing to do
    WHEN OTHERS THEN
        -- If procedure fails we raise to stop the transaction in triggers that call it
        RAISE;
END RECOMPUTE_EQUIPMENT_RESERVED;

/
--------------------------------------------------------
--  Constraints for Table TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "SUMMERCLUB"."TRANSACTIONS" MODIFY ("TRANSACTION_ID" NOT NULL ENABLE);
  ALTER TABLE "SUMMERCLUB"."TRANSACTIONS" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "SUMMERCLUB"."TRANSACTIONS" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "SUMMERCLUB"."TRANSACTIONS" ADD CONSTRAINT "PK_TRANSACTIONS" PRIMARY KEY ("ID_TR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SUMMERCLUB"."TRANSACTIONS" ADD CONSTRAINT "UK_TRANSACTION_ID" UNIQUE ("TRANSACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "SUMMERCLUB"."EMPLOYEES" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "SUMMERCLUB"."EMPLOYEES" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "SUMMERCLUB"."EMPLOYEES" ADD CONSTRAINT "CHK_EMP_EMAIL" CHECK (REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')) ENABLE;
  ALTER TABLE "SUMMERCLUB"."EMPLOYEES" ADD CONSTRAINT "PK_EMPLOYEES" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MANAGE
--------------------------------------------------------

  ALTER TABLE "SUMMERCLUB"."MANAGE" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "SUMMERCLUB"."MANAGE" MODIFY ("ID_EQ" NOT NULL ENABLE);
  ALTER TABLE "SUMMERCLUB"."MANAGE" ADD CONSTRAINT "PK_MANAGE" PRIMARY KEY ("CIN", "ID_EQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACTIVITIES
--------------------------------------------------------

  ALTER TABLE "SUMMERCLUB"."ACTIVITIES" MODIFY ("DURATION_MINUTES" NOT NULL ENABLE);
  ALTER TABLE "SUMMERCLUB"."ACTIVITIES" ADD CONSTRAINT "PK_ACTIVITY" PRIMARY KEY ("ID_A")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBERS
--------------------------------------------------------

  ALTER TABLE "SUMMERCLUB"."MEMBERS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "SUMMERCLUB"."MEMBERS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "SUMMERCLUB"."MEMBERS" ADD CONSTRAINT "CHK_MEMBER_EMAIL" CHECK (REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')) ENABLE;
  ALTER TABLE "SUMMERCLUB"."MEMBERS" ADD CONSTRAINT "PK_MEMBERS" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EQUIPEMENTS
--------------------------------------------------------

  ALTER TABLE "SUMMERCLUB"."EQUIPEMENTS" MODIFY ("RESERVED" NOT NULL ENABLE);
  ALTER TABLE "SUMMERCLUB"."EQUIPEMENTS" ADD UNIQUE ("EQUIP_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SUMMERCLUB"."EQUIPEMENTS" ADD PRIMARY KEY ("ID_EQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SUMMERCLUB"."EQUIPEMENTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SUMMERCLUB"."EQUIPEMENTS" MODIFY ("EQUIP_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPMENT_RESERVATIONS
--------------------------------------------------------

  ALTER TABLE "SUMMERCLUB"."EQUIPMENT_RESERVATIONS" ADD PRIMARY KEY ("ID_RESERVATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PARTICIPATE
--------------------------------------------------------

  ALTER TABLE "SUMMERCLUB"."PARTICIPATE" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "SUMMERCLUB"."PARTICIPATE" MODIFY ("ID_A" NOT NULL ENABLE);
  ALTER TABLE "SUMMERCLUB"."PARTICIPATE" ADD CONSTRAINT "PK_PARTICIPATE" PRIMARY KEY ("CIN", "ID_A")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "SUMMERCLUB"."EMPLOYEES" ADD CONSTRAINT "FK_EMPLOYEE_ACTIVITY" FOREIGN KEY ("ID_A")
	  REFERENCES "SUMMERCLUB"."ACTIVITIES" ("ID_A") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIPMENT_RESERVATIONS
--------------------------------------------------------

  ALTER TABLE "SUMMERCLUB"."EQUIPMENT_RESERVATIONS" ADD FOREIGN KEY ("ID_ACTIVITY")
	  REFERENCES "SUMMERCLUB"."ACTIVITIES" ("ID_A") ENABLE;
  ALTER TABLE "SUMMERCLUB"."EQUIPMENT_RESERVATIONS" ADD FOREIGN KEY ("ID_EQUIPMENT")
	  REFERENCES "SUMMERCLUB"."EQUIPEMENTS" ("ID_EQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MANAGE
--------------------------------------------------------

  ALTER TABLE "SUMMERCLUB"."MANAGE" ADD CONSTRAINT "FK_MANAGE_EMPLOYEE" FOREIGN KEY ("CIN")
	  REFERENCES "SUMMERCLUB"."EMPLOYEES" ("CIN") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARTICIPATE
--------------------------------------------------------

  ALTER TABLE "SUMMERCLUB"."PARTICIPATE" ADD CONSTRAINT "FK_PARTICIPATE_ACTIVITY" FOREIGN KEY ("ID_A")
	  REFERENCES "SUMMERCLUB"."ACTIVITIES" ("ID_A") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SUMMERCLUB"."PARTICIPATE" ADD CONSTRAINT "FK_PARTICIPATE_MEMBER" FOREIGN KEY ("CIN")
	  REFERENCES "SUMMERCLUB"."MEMBERS" ("CIN") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "SUMMERCLUB"."TRANSACTIONS" ADD CONSTRAINT "FK_TRANSACTIONS_EMPLOYEE" FOREIGN KEY ("CIN")
	  REFERENCES "SUMMERCLUB"."EMPLOYEES" ("CIN") ON DELETE SET NULL ENABLE;
