-- ===================================
-- RFID ACCESS LOG TABLE SETUP
-- Run this in your Oracle database
-- ===================================

-- Create sequence for auto-increment LOG_ID
CREATE SEQUENCE SUMMERCLUB.RFID_ACCESS_LOG_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Create the RFID Access Log table
CREATE TABLE SUMMERCLUB.RFID_ACCESS_LOG (
    LOG_ID NUMBER PRIMARY KEY,
    RFID_UID VARCHAR2(50) NOT NULL,
    MEMBER_CIN VARCHAR2(20),
    ACCESS_RESULT VARCHAR2(30) NOT NULL,
    ACCESS_TIME DATE DEFAULT SYSDATE NOT NULL,
    MEMBER_NAME VARCHAR2(100),
    DEVICE_LOCATION VARCHAR2(50) DEFAULT 'Main Entrance'
);

-- Create trigger to auto-increment LOG_ID
CREATE OR REPLACE TRIGGER SUMMERCLUB.RFID_ACCESS_LOG_TRG
BEFORE INSERT ON SUMMERCLUB.RFID_ACCESS_LOG
FOR EACH ROW
BEGIN
    IF :NEW.LOG_ID IS NULL THEN
        SELECT SUMMERCLUB.RFID_ACCESS_LOG_SEQ.NEXTVAL INTO :NEW.LOG_ID FROM DUAL;
    END IF;
END;
/

-- Create indexes for performance
CREATE INDEX IDX_RFID_ACCESS_LOG_UID ON SUMMERCLUB.RFID_ACCESS_LOG(RFID_UID);
CREATE INDEX IDX_RFID_ACCESS_LOG_TIME ON SUMMERCLUB.RFID_ACCESS_LOG(ACCESS_TIME);

-- Test the table
SELECT 'RFID Access Log Table created successfully!' AS STATUS FROM DUAL;

-- Show existing RFID cards for testing
SELECT 'Existing RFID Cards:' AS INFO FROM DUAL;
SELECT RFID_UID, CIN, CARD_STATUS FROM SUMMERCLUB.RFID_CARDS ORDER BY RFID_ID;

COMMIT;