--------------------------------------------------------
--  SUMMERCLUB Database Schema - Corrected Version
--  File created - November 6, 2025   
--------------------------------------------------------

-- =========================================================
-- STEP 1: CLEANUP - Drop existing objects safely
-- =========================================================

-- First, drop the problematic trigger specifically
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER SUMMERCLUB.ACTIVITY_ID_TRIGGER';
EXCEPTION
    WHEN OTHERS THEN NULL; -- Ignore if trigger doesn't exist
END;
/

-- Drop foreign key constraints first to avoid ORA-02449 errors
BEGIN
    FOR c IN (SELECT constraint_name, table_name 
              FROM user_constraints 
              WHERE constraint_type = 'R' 
              AND owner = 'SUMMERCLUB') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'ALTER TABLE SUMMERCLUB.' || c.table_name || ' DROP CONSTRAINT ' || c.constraint_name;
        EXCEPTION
            WHEN OTHERS THEN NULL; -- Ignore if constraint doesn't exist
        END;
    END LOOP;
END;
/

-- Drop tables with CASCADE CONSTRAINTS to handle any remaining references
BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE owner = 'SUMMERCLUB') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP TABLE SUMMERCLUB.' || t.table_name || ' CASCADE CONSTRAINTS';
        EXCEPTION
            WHEN OTHERS THEN NULL; -- Ignore if table doesn't exist
        END;
    END LOOP;
END;
/

-- Drop sequences
BEGIN
    FOR s IN (SELECT sequence_name FROM user_sequences WHERE sequence_owner = 'SUMMERCLUB') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP SEQUENCE SUMMERCLUB.' || s.sequence_name;
        EXCEPTION
            WHEN OTHERS THEN NULL; -- Ignore if sequence doesn't exist
        END;
    END LOOP;
END;
/

-- Drop triggers
BEGIN
    FOR t IN (SELECT trigger_name FROM user_triggers WHERE owner = 'SUMMERCLUB') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP TRIGGER SUMMERCLUB.' || t.trigger_name;
        EXCEPTION
            WHEN OTHERS THEN NULL; -- Ignore if trigger doesn't exist
        END;
    END LOOP;
END;
/

-- =========================================================
-- STEP 2: CREATE SEQUENCES
-- =========================================================

CREATE SEQUENCE SUMMERCLUB.ACTIVITY_ID_SEQ 
    MINVALUE 1 
    MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOORDER 
    NOCYCLE;

CREATE SEQUENCE SUMMERCLUB.EQUIPMENT_ID_SEQ 
    MINVALUE 1 
    MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOORDER 
    NOCYCLE;

CREATE SEQUENCE SUMMERCLUB.TRANSACTION_ID_SEQ 
    MINVALUE 1 
    MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOORDER 
    NOCYCLE;

-- =========================================================
-- STEP 3: CREATE TABLES (Parent tables first)
-- =========================================================

-- Create ACTIVITIES table (referenced by EMPLOYEES and PARTICIPATE)
CREATE TABLE SUMMERCLUB.ACTIVITIES (
    ID_A NUMBER,
    ACTIVITY_TYPE VARCHAR2(50 BYTE),
    EVENT_DATE DATE,
    EVENT_TIME TIMESTAMP(6),
    RESPONSIBLE VARCHAR2(100 BYTE),
    AGE_REQUIREMENT NUMBER(3,0),
    STATUS VARCHAR2(20 BYTE) DEFAULT 'Scheduled',
    DESCRIPTION CLOB,
    CAPACITY NUMBER(5,0),
    CREATED_DATE TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ACTIVITY PRIMARY KEY (ID_A)
);

-- Create MEMBERS table (referenced by PARTICIPATE and TRANSACTIONS)
CREATE TABLE SUMMERCLUB.MEMBERS (
    CIN VARCHAR2(50 BYTE),
    FIRST_NAME VARCHAR2(100 BYTE) NOT NULL,
    LAST_NAME VARCHAR2(100 BYTE) NOT NULL,
    GENDER VARCHAR2(10 BYTE),
    AGE NUMBER,
    EMAIL VARCHAR2(255 BYTE),
    PHONE VARCHAR2(20 BYTE),
    SUBSCRIPTION_PLAN VARCHAR2(50 BYTE),
    JOIN_DATE DATE,
    PHOTO BLOB,
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_MEMBERS PRIMARY KEY (CIN),
    CONSTRAINT CHK_MEMBER_EMAIL CHECK (REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'))
);

-- Create EQUIPEMENTS table (referenced by MANAGE)
CREATE TABLE SUMMERCLUB.EQUIPEMENTS (
    ID_EQ NUMBER,
    EQUIP_CODE VARCHAR2(50 BYTE) NOT NULL,
    NAME VARCHAR2(100 BYTE) NOT NULL,
    CATEGORY VARCHAR2(50 BYTE),
    TOTAL_QUANTITY NUMBER(5,0),
    AVAILABLE NUMBER(5,0),
    IN_USE NUMBER(5,0),
    UNDER_MAINTENANCE NUMBER(5,0),
    STATUS VARCHAR2(20 BYTE) DEFAULT 'Available',
    BRAND VARCHAR2(50 BYTE),
    MODEL VARCHAR2(50 BYTE),
    PURCHASE_DATE DATE,
    PURCHASE_PRICE NUMBER(10,2),
    LOCATION VARCHAR2(100 BYTE),
    NOTES CLOB,
    CREATED_DATE TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_EQUIPEMENTS PRIMARY KEY (ID_EQ),
    CONSTRAINT UK_EQUIP_CODE UNIQUE (EQUIP_CODE)
);

-- Create EMPLOYEES table (references ACTIVITIES, referenced by MANAGE and TRANSACTIONS)
CREATE TABLE SUMMERCLUB.EMPLOYEES (
    CIN VARCHAR2(50 BYTE),
    FIRST_NAME VARCHAR2(100 BYTE) NOT NULL,
    LAST_NAME VARCHAR2(100 BYTE) NOT NULL,
    POSITION VARCHAR2(50 BYTE),
    DEPARTMENT VARCHAR2(50 BYTE),
    HIRE_DATE DATE,
    STATUS VARCHAR2(20 BYTE) DEFAULT 'Active',
    AGE NUMBER(3,0),
    GENDER VARCHAR2(10 BYTE),
    EMAIL VARCHAR2(255 BYTE),
    PHONE VARCHAR2(20 BYTE),
    SALARY NUMBER(10,2),
    PASSWORD VARCHAR2(255 BYTE),
    PHOTO BLOB,
    ID_A NUMBER,
    CREATED_DATE TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_EMPLOYEES PRIMARY KEY (CIN),
    CONSTRAINT CHK_EMP_EMAIL CHECK (REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')),
    CONSTRAINT FK_EMPLOYEE_ACTIVITY FOREIGN KEY (ID_A) REFERENCES SUMMERCLUB.ACTIVITIES(ID_A) ON DELETE SET NULL
);

-- Create PARTICIPATE table (junction table - references MEMBERS and ACTIVITIES)
CREATE TABLE SUMMERCLUB.PARTICIPATE (
    CIN VARCHAR2(50 BYTE) NOT NULL,
    ID_A NUMBER NOT NULL,
    CONSTRAINT PK_PARTICIPATE PRIMARY KEY (CIN, ID_A),
    CONSTRAINT FK_PARTICIPATE_MEMBER FOREIGN KEY (CIN) REFERENCES SUMMERCLUB.MEMBERS(CIN) ON DELETE CASCADE,
    CONSTRAINT FK_PARTICIPATE_ACTIVITY FOREIGN KEY (ID_A) REFERENCES SUMMERCLUB.ACTIVITIES(ID_A) ON DELETE CASCADE
);

-- Create MANAGE table (junction table - references EMPLOYEES and EQUIPEMENTS)
CREATE TABLE SUMMERCLUB.MANAGE (
    CIN VARCHAR2(50 BYTE) NOT NULL,
    ID_EQ NUMBER NOT NULL,
    CONSTRAINT PK_MANAGE PRIMARY KEY (CIN, ID_EQ),
    CONSTRAINT FK_MANAGE_EMPLOYEE FOREIGN KEY (CIN) REFERENCES SUMMERCLUB.EMPLOYEES(CIN) ON DELETE CASCADE,
    CONSTRAINT FK_MANAGE_EQUIPMENT FOREIGN KEY (ID_EQ) REFERENCES SUMMERCLUB.EQUIPEMENTS(ID_EQ) ON DELETE CASCADE
);

-- Create TRANSACTIONS table (references EMPLOYEES)
CREATE TABLE SUMMERCLUB.TRANSACTIONS (
    ID_TR NUMBER,
    TRANSACTION_ID VARCHAR2(100 BYTE) NOT NULL,
    PAYMENT_DATE DATE,
    DESCRIPTION VARCHAR2(500 BYTE),
    PAYMENT_TYPE VARCHAR2(50 BYTE),
    AMOUNT NUMBER(10,2) NOT NULL,
    PAYMENT_METHOD VARCHAR2(50 BYTE),
    STATUS VARCHAR2(20 BYTE) DEFAULT 'Pending',
    MEMBER_ID VARCHAR2(50 BYTE) NOT NULL,
    CIN VARCHAR2(50 BYTE),
    CREATED_DATE TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TRANSACTIONS PRIMARY KEY (ID_TR),
    CONSTRAINT UK_TRANSACTION_ID UNIQUE (TRANSACTION_ID),
    CONSTRAINT FK_TRANSACTIONS_EMPLOYEE FOREIGN KEY (CIN) REFERENCES SUMMERCLUB.EMPLOYEES(CIN) ON DELETE SET NULL
);

-- =========================================================
-- STEP 4: CREATE TRIGGERS FOR AUTO-INCREMENT
-- =========================================================

-- Trigger for ACTIVITIES (matches your original trigger name)
CREATE OR REPLACE TRIGGER SUMMERCLUB.ACTIVITY_ID_TRIGGER
    BEFORE INSERT ON SUMMERCLUB.ACTIVITIES
    FOR EACH ROW
BEGIN
    IF :NEW.ID_A IS NULL THEN
        :NEW.ID_A := SUMMERCLUB.ACTIVITY_ID_SEQ.NEXTVAL;
    END IF;
END;
/

-- Enable the trigger explicitly
ALTER TRIGGER SUMMERCLUB.ACTIVITY_ID_TRIGGER ENABLE;

-- Check trigger status
SELECT trigger_name, status FROM user_triggers WHERE trigger_name = 'ACTIVITY_ID_TRIGGER';

-- Trigger for EQUIPEMENTS
CREATE OR REPLACE TRIGGER SUMMERCLUB.TRG_EQUIPMENT_ID
    BEFORE INSERT ON SUMMERCLUB.EQUIPEMENTS
    FOR EACH ROW
BEGIN
    IF :NEW.ID_EQ IS NULL THEN
        :NEW.ID_EQ := SUMMERCLUB.EQUIPMENT_ID_SEQ.NEXTVAL;
    END IF;
END;
/

-- Trigger for TRANSACTIONS
CREATE OR REPLACE TRIGGER SUMMERCLUB.TRG_TRANSACTION_ID
    BEFORE INSERT ON SUMMERCLUB.TRANSACTIONS
    FOR EACH ROW
BEGIN
    IF :NEW.ID_TR IS NULL THEN
        :NEW.ID_TR := SUMMERCLUB.TRANSACTION_ID_SEQ.NEXTVAL;
    END IF;
END;
/

-- =========================================================
-- STEP 5: INSERT SAMPLE DATA
-- =========================================================

-- Insert Activities first (no dependencies)
INSERT INTO SUMMERCLUB.ACTIVITIES (ACTIVITY_TYPE, EVENT_DATE, EVENT_TIME, RESPONSIBLE, AGE_REQUIREMENT, STATUS, CAPACITY) 
VALUES ('Group Class', DATE '2025-11-05', TIMESTAMP '2025-11-05 20:03:33', 'Khalil', 5, 'Scheduled', 30);

INSERT INTO SUMMERCLUB.ACTIVITIES (ACTIVITY_TYPE, EVENT_DATE, EVENT_TIME, RESPONSIBLE, AGE_REQUIREMENT, STATUS, CAPACITY) 
VALUES ('Group Class', DATE '2026-02-01', TIMESTAMP '2026-02-01 14:33:00', 'Yasmine Hidri', 18, 'In Progress', 30);

-- Insert Members (no dependencies)
INSERT INTO SUMMERCLUB.MEMBERS (CIN, FIRST_NAME, LAST_NAME, GENDER, AGE, EMAIL, PHONE, SUBSCRIPTION_PLAN, JOIN_DATE) 
VALUES ('11111111', 'Khalil', 'Cherif', 'Male', 25, 'khalil05cherif@gmail.com', '55256271', 'Monthly', DATE '2000-01-01');

INSERT INTO SUMMERCLUB.MEMBERS (CIN, FIRST_NAME, LAST_NAME, GENDER, AGE, EMAIL, PHONE, SUBSCRIPTION_PLAN, JOIN_DATE) 
VALUES ('12345678', 'John', 'Doe', 'Male', 18, 'john.doe@example.com', '55567876', 'Monthly', DATE '2025-11-05');

INSERT INTO SUMMERCLUB.MEMBERS (CIN, FIRST_NAME, LAST_NAME, GENDER, AGE, EMAIL, PHONE, SUBSCRIPTION_PLAN, JOIN_DATE) 
VALUES ('11112222', 'Ahmad', 'Ali', 'Male', 18, 'ahmad@example.com', '55555555', 'Monthly', DATE '2025-11-05');

INSERT INTO SUMMERCLUB.MEMBERS (CIN, FIRST_NAME, LAST_NAME, GENDER, AGE, EMAIL, PHONE, SUBSCRIPTION_PLAN, JOIN_DATE) 
VALUES ('11111115', 'Sara', 'Ben Salah', 'Female', 18, 'sara@example.com', '11111111', 'Monthly', DATE '2025-11-05');

-- Insert Equipment (no dependencies)
INSERT INTO SUMMERCLUB.EQUIPEMENTS (EQUIP_CODE, NAME, CATEGORY, TOTAL_QUANTITY, AVAILABLE, IN_USE, UNDER_MAINTENANCE, STATUS, BRAND, LOCATION) 
VALUES ('EQ001', 'Swimming Pool Lane Ropes', 'Pool Equipment', 10, 8, 2, 0, 'Available', 'AquaTech', 'Pool Area');

INSERT INTO SUMMERCLUB.EQUIPEMENTS (EQUIP_CODE, NAME, CATEGORY, TOTAL_QUANTITY, AVAILABLE, IN_USE, UNDER_MAINTENANCE, STATUS, BRAND, LOCATION) 
VALUES ('EQ002', 'Tennis Rackets', 'Sports Equipment', 20, 15, 3, 2, 'Available', 'Wilson', 'Tennis Court');

-- Insert Employees (references Activities)
INSERT INTO SUMMERCLUB.EMPLOYEES (CIN, FIRST_NAME, LAST_NAME, POSITION, DEPARTMENT, HIRE_DATE, STATUS, AGE, GENDER, EMAIL, PHONE, SALARY, PASSWORD, ID_A) 
VALUES ('EMP001', 'Khalil', 'Fakroun', 'Activity Manager', 'Activity Management', DATE '2025-11-05', 'Active', 25, 'Male', 'khalil@summerclub.com', '55555555', 1200.00, 'password123', 1);

INSERT INTO SUMMERCLUB.EMPLOYEES (CIN, FIRST_NAME, LAST_NAME, POSITION, DEPARTMENT, HIRE_DATE, STATUS, AGE, GENDER, EMAIL, PHONE, SALARY, PASSWORD, ID_A) 
VALUES ('EMP002', 'Yasmine', 'Hidri', 'Senior Instructor', 'Activity Management', DATE '2025-11-05', 'Active', 20, 'Female', 'yasmine@summerclub.com', '55555556', 1000.00, 'password456', 2);

-- Insert Participate relationships (references Members and Activities)
INSERT INTO SUMMERCLUB.PARTICIPATE (CIN, ID_A) VALUES ('11111111', 1);
INSERT INTO SUMMERCLUB.PARTICIPATE (CIN, ID_A) VALUES ('12345678', 1);
INSERT INTO SUMMERCLUB.PARTICIPATE (CIN, ID_A) VALUES ('11112222', 2);

-- Insert Manage relationships (references Employees and Equipment)
INSERT INTO SUMMERCLUB.MANAGE (CIN, ID_EQ) VALUES ('EMP001', 1);
INSERT INTO SUMMERCLUB.MANAGE (CIN, ID_EQ) VALUES ('EMP002', 2);

-- Insert Transactions (references Employees)
INSERT INTO SUMMERCLUB.TRANSACTIONS (TRANSACTION_ID, PAYMENT_DATE, DESCRIPTION, PAYMENT_TYPE, AMOUNT, PAYMENT_METHOD, STATUS, MEMBER_ID, CIN) 
VALUES ('TXN001', DATE '2025-11-05', 'Monthly membership fee', 'Subscription', 50.00, 'Credit Card', 'Completed', '11111111', 'EMP001');

INSERT INTO SUMMERCLUB.TRANSACTIONS (TRANSACTION_ID, PAYMENT_DATE, DESCRIPTION, PAYMENT_TYPE, AMOUNT, PAYMENT_METHOD, STATUS, MEMBER_ID, CIN) 
VALUES ('TXN002', DATE '2025-11-05', 'Equipment rental', 'Rental', 25.00, 'Cash', 'Completed', '12345678', 'EMP002');

-- =========================================================
-- STEP 6: VERIFICATION QUERIES
-- =========================================================

-- Check if all tables were created successfully
SELECT 'Tables created successfully' AS status FROM dual;

-- Verify data insertion
SELECT 'ACTIVITIES: ' || COUNT(*) || ' records' AS summary FROM SUMMERCLUB.ACTIVITIES
UNION ALL
SELECT 'MEMBERS: ' || COUNT(*) || ' records' FROM SUMMERCLUB.MEMBERS
UNION ALL
SELECT 'EMPLOYEES: ' || COUNT(*) || ' records' FROM SUMMERCLUB.EMPLOYEES
UNION ALL
SELECT 'EQUIPEMENTS: ' || COUNT(*) || ' records' FROM SUMMERCLUB.EQUIPEMENTS
UNION ALL
SELECT 'PARTICIPATE: ' || COUNT(*) || ' records' FROM SUMMERCLUB.PARTICIPATE
UNION ALL
SELECT 'MANAGE: ' || COUNT(*) || ' records' FROM SUMMERCLUB.MANAGE
UNION ALL
SELECT 'TRANSACTIONS: ' || COUNT(*) || ' records' FROM SUMMERCLUB.TRANSACTIONS;

-- Check foreign key relationships
SELECT 
    c.constraint_name,
    c.table_name,
    c.constraint_type,
    c.status
FROM user_constraints c
WHERE c.owner = 'SUMMERCLUB'
AND c.constraint_type = 'R'
ORDER BY c.table_name;

COMMIT;

-- Success message
SELECT 'Database schema created successfully!' AS message FROM dual;